global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#vitaliy_lopin'
