version: '3'
services:
  fluentd:
    image: ${USERNAME}/fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - front_net

  elasticsearch:
    image: elasticsearch:6.4.1
    expose:
      - 9200
    ports:
      - "9200:9200"
    networks:
      - front_net

  kibana:
    image: kibana:6.4.1
    ports:
      - "5601:5601"
    networks:
      - front_net

networks:
  front_net:
  back_net:
